[package]
name = "talenta"
version = "1.0.0"
authors = ["el7cosmos <el@elabee.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
clap = { version = "2.33", features = ["color", "yaml"] }
confy = "0.4"
dialoguer = "0.6"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
url = "2.1"